"""
PrusaSlicer CLI bridge — slices STL models into G-code.

Finds the ``prusa-slicer-console`` executable automatically and invokes
it with a printer profile for the Prusa MK3S.  All slicing parameters
live in ``configs/slicer_profile.ini``; if the file doesn't exist a
sensible default is generated on first use.
"""

from __future__ import annotations

import logging
import shutil
import subprocess
from pathlib import Path

log = logging.getLogger("manufacturerAI.gcode.slicer")

# ── Locate PrusaSlicer ─────────────────────────────────────────────

_CANDIDATES = [
    r"C:\Program Files\Prusa3D\PrusaSlicer\prusa-slicer-console.exe",
    r"C:\Program Files (x86)\Prusa3D\PrusaSlicer\prusa-slicer-console.exe",
]


def find_prusaslicer() -> str | None:
    """Return the path to ``prusa-slicer-console``, or *None*."""
    path = shutil.which("prusa-slicer-console")
    if path:
        return path
    for c in _CANDIDATES:
        if Path(c).exists():
            return c
    return None


# ── Default slicer profile ─────────────────────────────────────────

_DEFAULT_PROFILE = """\
# PrusaSlicer CLI profile — Prusa MK3S, PLA, 0.2 mm layers
# Generated by ManufacturerAI — edit freely.

# --- Printer ---
printer_model = MK3S
gcode_flavor = marlin
bed_shape = 0x0,250x0,250x210,0x210
nozzle_diameter = 0.4
start_gcode = M862.3 P \\"MK3S\\" ; printer model check\\nM862.1 P0.4 ; nozzle diameter check\\nM115 U3.14.0 ; tell printer latest fw version\\nG28 W ; home all without mesh bed level\\nG80 ; mesh bed leveling\\nG1 Z0.20 F720\\nG1 Y-3 F1000 ; go outside print area\\nG92 E0\\nG1 X60 E9 F1000 ; intro line\\nG1 X100 E12.5 F1000 ; intro line\\nG92 E0\\nM221 S95
end_gcode = G4 ; wait\\nM104 S0 ; turn off temperature\\nM140 S0 ; turn off heatbed\\nM107 ; turn off fan\\nG1 X0 Y200 ; home X axis\\nM84 ; disable motors

# --- Print ---
layer_height = 0.2
first_layer_height = 0.2
perimeters = 3
top_solid_layers = 4
bottom_solid_layers = 3
fill_density = 15%
fill_pattern = grid
infill_speed = 60
perimeter_speed = 45
travel_speed = 150

# --- Temperatures ---
temperature = 215
first_layer_temperature = 215
bed_temperature = 60
first_layer_bed_temperature = 60

# --- Retraction ---
retract_length = 0.8
retract_speed = 35
retract_lift = 0.6

# --- Cooling ---
fan_always_on = 1
min_fan_speed = 100
max_fan_speed = 100
bridge_fan_speed = 100

# --- Ironing ---
ironing = 1
ironing_type = top
ironing_flowrate = 15%
ironing_speed = 15
ironing_spacing = 0.1
"""


def ensure_profile(profile_path: Path) -> Path:
    """Create the default slicer profile if it doesn't exist yet."""
    if not profile_path.exists():
        profile_path.parent.mkdir(parents=True, exist_ok=True)
        profile_path.write_text(_DEFAULT_PROFILE, encoding="utf-8")
        log.info("Created default slicer profile: %s", profile_path)
    return profile_path


# ── Slice ──────────────────────────────────────────────────────────

def slice_stl(
    stl_path: Path,
    output_gcode: Path | None = None,
    profile_path: Path | None = None,
    *,
    timeout_s: int = 300,
) -> tuple[bool, str, Path | None]:
    """Slice *stl_path* and write G-code.

    Parameters
    ----------
    stl_path : Path
        Input STL file.
    output_gcode : Path, optional
        Where to write the ``.gcode`` file.  Defaults to
        ``stl_path.with_suffix('.gcode')``.
    profile_path : Path, optional
        ``--load`` ini file.  When *None* the default profile under
        ``configs/slicer_profile.ini`` is used (created if missing).
    timeout_s : int
        CLI timeout in seconds.

    Returns
    -------
    (ok, message, gcode_path_or_none)
    """
    exe = find_prusaslicer()
    if not exe:
        return False, "PrusaSlicer not found on this system.", None

    if profile_path is None:
        cfg_dir = Path(__file__).resolve().parents[2] / "configs"
        profile_path = ensure_profile(cfg_dir / "slicer_profile.ini")

    if output_gcode is None:
        output_gcode = stl_path.with_suffix(".gcode")

    cmd = [
        exe,
        "--export-gcode",
        "--load", str(profile_path),
        "--output", str(output_gcode),
        str(stl_path),
    ]

    log.info("Slicing: %s", " ".join(cmd))

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout_s,
        )
        stderr = result.stderr.strip()
        if result.returncode == 0 and output_gcode.exists():
            log.info("Slicing succeeded: %s", output_gcode)
            return True, stderr or "OK", output_gcode
        return False, stderr or f"PrusaSlicer exited with code {result.returncode}", None
    except subprocess.TimeoutExpired:
        return False, f"PrusaSlicer timed out ({timeout_s}s).", None
    except Exception as e:
        return False, str(e), None
