"""
PrusaSlicer CLI bridge — slices STL models into G-code.

Finds the ``prusa-slicer-console`` executable automatically and invokes
it with a printer profile.  Supports multiple printers (MK3S, MK3S+, Core One+).
All slicing parameters live in ``configs/slicer_profile*.ini``; defaults
are generated on first use.
"""

from __future__ import annotations

import logging
import shutil
import subprocess
from pathlib import Path

log = logging.getLogger("manufacturerAI.gcode.slicer")

# ── Locate PrusaSlicer ─────────────────────────────────────────────

_CANDIDATES = [
    r"C:\Program Files\Prusa3D\PrusaSlicer\prusa-slicer-console.exe",
    r"C:\Program Files (x86)\Prusa3D\PrusaSlicer\prusa-slicer-console.exe",
]


def find_prusaslicer() -> str | None:
    """Return the path to ``prusa-slicer-console``, or *None*."""
    path = shutil.which("prusa-slicer-console")
    if path:
        return path
    for c in _CANDIDATES:
        if Path(c).exists():
            return c
    return None


_GUI_CANDIDATES = [
    r"C:\Program Files\Prusa3D\PrusaSlicer\prusa-slicer.exe",
    r"C:\Program Files (x86)\Prusa3D\PrusaSlicer\prusa-slicer.exe",
]


def find_prusaslicer_gui() -> str | None:
    """Return the path to the *GUI* ``prusa-slicer`` executable.

    The ``--gcodeviewer`` flag requires the GUI binary, not the
    headless ``prusa-slicer-console``.
    """
    path = shutil.which("prusa-slicer")
    if path:
        return path
    for c in _GUI_CANDIDATES:
        if Path(c).exists():
            return c
    return None


# ── Printer definitions ────────────────────────────────────────────

from dataclasses import dataclass


@dataclass(frozen=True)
class PrinterDef:
    """Static definition of a supported 3D printer."""
    id: str               # short key, e.g. "mk3s"
    label: str            # human-readable, e.g. "Prusa MK3S"
    bed_width: float      # mm
    bed_depth: float      # mm
    profile_filename: str # ini in configs/
    # PrusaSlicer built-in profile names (None → use --load only)
    native_printer: str | None = None
    native_print: str | None = None
    native_material: str | None = None
    # Thumbnail sizes for --thumbnails CLI flag (None → no thumbnails)
    thumbnails: str | None = None


PRINTERS: dict[str, PrinterDef] = {
    "mk3s": PrinterDef(
        id="mk3s",
        label="Prusa MK3S",
        bed_width=250.0,
        bed_depth=210.0,
        profile_filename="slicer_profile.ini",
    ),
    "mk3s_plus": PrinterDef(
        id="mk3s_plus",
        label="Prusa i3 MK3S+",
        bed_width=250.0,
        bed_depth=210.0,
        profile_filename="slicer_profile_mk3s_plus.ini",
    ),
    "coreone": PrinterDef(
        id="coreone",
        label="Prusa Core One+",
        bed_width=250.0,
        bed_depth=220.0,
        profile_filename="slicer_profile_coreone.ini",
        native_printer="Prusa CORE One HF0.4 nozzle",
        native_print="0.20mm BALANCED @COREONE HF0.4",
        native_material="Prusament PLA @COREONE HF0.4",
        thumbnails="16x16/PNG,220x124/PNG",
    ),
}

DEFAULT_PRINTER = "mk3s"


def get_printer(printer_id: str | None = None) -> PrinterDef:
    """Return the *PrinterDef* for *printer_id* (falls back to default)."""
    pid = (printer_id or DEFAULT_PRINTER).lower().strip()
    if pid not in PRINTERS:
        log.warning("Unknown printer '%s' — falling back to %s", pid, DEFAULT_PRINTER)
        pid = DEFAULT_PRINTER
    return PRINTERS[pid]


# ── Default slicer profiles ────────────────────────────────────────

_DEFAULT_PROFILES: dict[str, str] = {
    "slicer_profile.ini": """\
# PrusaSlicer CLI profile — Prusa MK3S, PLA, 0.2 mm layers
# Generated by ManufacturerAI — edit freely.

# --- Printer ---
printer_model = MK3S
gcode_flavor = marlin
bed_shape = 0x0,250x0,250x210,0x210
nozzle_diameter = 0.4
start_gcode = M862.3 P \\"MK3S\\" ; printer model check\\nM862.1 P0.4 ; nozzle diameter check\\nM115 U3.14.0 ; tell printer latest fw version\\nG28 W ; home all without mesh bed level\\nG80 ; mesh bed leveling\\nG1 Z0.20 F720\\nG1 Y-3 F1000 ; go outside print area\\nG92 E0\\nG1 X60 E9 F1000 ; intro line\\nG1 X100 E12.5 F1000 ; intro line\\nG92 E0\\nM221 S95
end_gcode = G4 ; wait\\nM104 S0 ; turn off temperature\\nM140 S0 ; turn off heatbed\\nM107 ; turn off fan\\nG1 X0 Y200 ; home X axis\\nM84 ; disable motors

# --- Print ---
layer_height = 0.2
first_layer_height = 0.2
perimeters = 3
top_solid_layers = 4
bottom_solid_layers = 3
fill_density = 15%
fill_pattern = grid
infill_speed = 60
perimeter_speed = 45
travel_speed = 150

# --- Temperatures ---
temperature = 215
first_layer_temperature = 215
bed_temperature = 60
first_layer_bed_temperature = 60

# --- Retraction ---
retract_length = 0.8
retract_speed = 35
retract_lift = 0.6

# --- Cooling ---
fan_always_on = 1
min_fan_speed = 100
max_fan_speed = 100
bridge_fan_speed = 100

# --- Support ---
support_material = 0

# --- Travel / retraction improvements ---
wipe = 1
avoid_crossing_perimeters = 1
avoid_crossing_perimeters_max_detour = 0
seam_position = aligned

# --- Ironing ---
ironing = 1
ironing_type = top
ironing_flowrate = 15%
ironing_speed = 15
ironing_spacing = 0.1
""",
    "slicer_profile_mk3s_plus.ini": """\
# PrusaSlicer CLI profile — Prusa i3 MK3S+, PLA, 0.2 mm layers
# Generated by ManufacturerAI — edit freely.

# --- Printer ---
printer_model = MK3SPLUS
gcode_flavor = marlin
bed_shape = 0x0,250x0,250x210,0x210
nozzle_diameter = 0.4
start_gcode = M862.3 P \\"MK3SPLUS\\" ; printer model check\\nM862.1 P0.4 ; nozzle diameter check\\nM115 U3.14.0 ; tell printer latest fw version\\nG28 W ; home all without mesh bed level\\nG80 ; mesh bed leveling\\nG1 Z0.20 F720\\nG1 Y-3 F1000 ; go outside print area\\nG92 E0\\nG1 X60 E9 F1000 ; intro line\\nG1 X100 E12.5 F1000 ; intro line\\nG92 E0\\nM221 S95
end_gcode = G4 ; wait\\nM104 S0 ; turn off temperature\\nM140 S0 ; turn off heatbed\\nM107 ; turn off fan\\nG1 X0 Y200 ; home X axis\\nM84 ; disable motors

# --- Print ---
layer_height = 0.2
first_layer_height = 0.2
perimeters = 3
top_solid_layers = 4
bottom_solid_layers = 3
fill_density = 15%
fill_pattern = grid
infill_speed = 60
perimeter_speed = 45
travel_speed = 150

# --- Temperatures ---
temperature = 215
first_layer_temperature = 215
bed_temperature = 60
first_layer_bed_temperature = 60

# --- Retraction ---
retract_length = 0.8
retract_speed = 35
retract_lift = 0.6

# --- Cooling ---
fan_always_on = 1
min_fan_speed = 100
max_fan_speed = 100
bridge_fan_speed = 100

# --- Support ---
support_material = 0

# --- Travel / retraction improvements ---
wipe = 1
avoid_crossing_perimeters = 1
avoid_crossing_perimeters_max_detour = 0
seam_position = aligned

# --- Ironing ---
ironing = 1
ironing_type = top
ironing_flowrate = 15%
ironing_speed = 15
ironing_spacing = 0.1
""",
    "slicer_profile_coreone.ini": """\
# PrusaSlicer CLI overrides — Prusa Core One+ HF0.4
# Applied on top of the built-in "0.20mm BALANCED @COREONE HF0.4" profile.
# Generated by ManufacturerAI — edit freely.

# --- Output format ---
# Force ASCII G-code so our postprocessor can do text manipulation.
# The pipeline converts the staged .gcode → .bgcode afterwards,
# so the printer receives native binary G-code with no warnings.
binary_gcode = 0

# --- Settings IDs (must match built-in profile names) ---
printer_settings_id = Prusa CORE One HF0.4 nozzle
print_settings_id = 0.20mm BALANCED @COREONE HF0.4
filament_settings_id = Prusament PLA @COREONE HF0.4

# --- Thumbnails (displayed on the Core One screen) ---
thumbnails = 16x16/PNG, 220x124/PNG
thumbnails_format = PNG

# --- Infill ---
fill_density = 5%

# --- Support ---
# Disabled: the enclosure geometry prints cleanly without supports.
# PrusaSlicer handles overhangs via bridging and overhang perimeters.
support_material = 0

# --- Travel improvements ---
# Wipe nozzle before retraction to reduce ooze blob
wipe = 1
# Route travel moves around already-printed perimeters
# (prevents nozzle from scraping across printed surfaces)
avoid_crossing_perimeters = 1
# Limit detour to 3x direct distance — prevents excessively long
# travel paths around pinholes that increase ooze time.
avoid_crossing_perimeters_max_detour = 3
# Align Z-seam so layer start/stop blobs form a single
# line instead of random dots across the surface
seam_position = aligned
# Disable travel ramping (diagonal Z-ramp); use a clean Z-hop instead
# so the nozzle lifts before traveling and doesn't drag across the surface
travel_ramping_lift = 0
filament_travel_ramping_lift = 0
# --- Retraction ---
# Use Prusa's factory defaults for retraction distance and speed.
# The Core One HF 0.4 has a short melt zone with active heat-break
# cooling (M142 S36).  The built-in profile uses ~0.8mm retraction
# which is tuned for this geometry.  Overriding to 2.0mm caused
# semi-molten filament to be pulled into the cold zone -> clogging.

# --- Temperature ---
# The built-in "Prusament PLA @COREONE HF0.4" profile defaults to 230 C.
# 225 C is a compromise: low enough to reduce ooze vs 230, but high
# enough to fully melt filament in the HF nozzle's large melt zone.
# 215 C caused clogs — the stiffer melt couldn't re-flow after retraction.
temperature = 225
first_layer_temperature = 225
filament_first_layer_temperature = 225
filament_temperature = 225

# --- Retraction refinements ---
# Retract 70 % of the distance *before* the wipe move so the full
# retraction completes even if the wipe path is short.  Without this,
# short wipes leave partial retraction -> net positive E accumulation.
retract_before_wipe = 70%
filament_retract_before_wipe = 70%
# Retract on short travels too — reduces stringing around pinholes.
retract_before_travel = 0.8

# --- Ironing ---
ironing = 1
ironing_type = top
ironing_flowrate = 15%
ironing_speed = 15
ironing_spacing = 0.1
""",
}


def ensure_profile(profile_path: Path) -> Path:
    """Create a slicer profile if it doesn't exist yet."""
    if not profile_path.exists():
        profile_path.parent.mkdir(parents=True, exist_ok=True)
        default_content = _DEFAULT_PROFILES.get(profile_path.name, "")
        if default_content:
            profile_path.write_text(default_content, encoding="utf-8")
            log.info("Created default slicer profile: %s", profile_path)
        else:
            log.warning("No default content for profile %s", profile_path.name)
    return profile_path


# ── Slice ──────────────────────────────────────────────────────────

def slice_stl(
    stl_path: Path,
    output_gcode: Path | None = None,
    profile_path: Path | None = None,
    *,
    printer: str | None = None,
    timeout_s: int = 300,
) -> tuple[bool, str, Path | None]:
    """Slice *stl_path* and write G-code.

    Parameters
    ----------
    stl_path : Path
        Input STL file.
    output_gcode : Path, optional
        Where to write the ``.gcode`` file.  Defaults to
        ``stl_path.with_suffix('.gcode')``.
    profile_path : Path, optional
        ``--load`` ini file.  When *None* the printer-specific
        default profile is used (created if missing).
    printer : str, optional
        Printer id (``"mk3s"``, ``"mk3s_plus"``, or ``"coreone"``).
        Determines which default profile to use when *profile_path* is None.
    timeout_s : int
        CLI timeout in seconds.

    Returns
    -------
    (ok, message, gcode_path_or_none)
    """
    exe = find_prusaslicer()
    if not exe:
        return False, "PrusaSlicer not found on this system.", None

    pdef = get_printer(printer)

    if profile_path is None:
        cfg_dir = Path(__file__).resolve().parents[2] / "configs"
        profile_path = ensure_profile(cfg_dir / pdef.profile_filename)

    if output_gcode is None:
        output_gcode = stl_path.with_suffix(".gcode")

    cmd = [exe, "--export-gcode"]

    # Use built-in PrusaSlicer profiles when available (embeds correct
    # printer_settings_id / print_settings_id / filament_settings_id
    # metadata so the firmware doesn't show compatibility warnings).
    if pdef.native_printer:
        cmd += ["--printer-profile", pdef.native_printer]
    if pdef.native_print:
        cmd += ["--print-profile", pdef.native_print]
    if pdef.native_material:
        cmd += ["--material-profile", pdef.native_material]

    # --load applies our overrides (ironing, support, binary_gcode=0, …)
    # on top of the built-in profile.
    cmd += ["--load", str(profile_path)]

    # Explicitly request thumbnails — the CLI ignores the profile
    # setting unless passed on the command line.
    if pdef.thumbnails:
        cmd += ["--thumbnails", pdef.thumbnails]

    cmd += ["--output", str(output_gcode), str(stl_path)]

    log.info("Slicing: %s", " ".join(cmd))

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout_s,
        )
        stderr = result.stderr.strip()
        if result.returncode == 0 and output_gcode.exists():
            log.info("Slicing succeeded: %s", output_gcode)
            return True, stderr or "OK", output_gcode
        return False, stderr or f"PrusaSlicer exited with code {result.returncode}", None
    except subprocess.TimeoutExpired:
        return False, f"PrusaSlicer timed out ({timeout_s}s).", None
    except Exception as e:
        return False, str(e), None
